### ISSUE TITLE
Can't Get to Mobile Challenges by Year

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/mitre-cyber-academy.github.io#8]
On mobile you can't select challenges by year because the link in the image of the ctf-utils will be selected even if you select a year from the dropdown.

Suggestion: Remove image link to repository.

**Comment by rbclark** [comment]
So there is more to this issue, Even if I remove the image it doesn't matter. I actually took the code for the default dropdowns on the 2.3.2 bootstrap docs and injected it straight in and even that fails. I wonder if this is a bug in the (very old) version of bootstrap we are using. I may try bumping the bootstrap version and see if that helps.

**Comment by rbclark** [comment]
I have a fix for this in a branch however it cannot be merged until the updates to the training site are finished since I broke the learn page and didn't care to fix it since it is being rewritten right now anyway.
